# Generated by Django 4.1.7 on 2023-03-03 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomerUserApp', '0007_alter_customeruser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], max_length=20)),
                ('receiver_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='CustomerUserApp.customeruser')),
                ('sender_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='CustomerUserApp.customeruser')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
