# Generated by Django 4.1.7 on 2023-03-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdrawal'), ('T', 'Transfer')], max_length=20),
        ),
    ]
