# Generated by Django 4.1.7 on 2023-03-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionApp', '0002_alter_banktransaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='receiver',
            new_name='receiver_email',
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
