# Generated by Django 4.1.7 on 2023-03-03 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerUserApp', '0007_alter_customeruser_password'),
        ('transactionApp', '0003_rename_receiver_banktransaction_receiver_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='receiver_name',
            new_name='reference',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='receiver_email',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='sender_email',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='CustomerUserApp.customeruser', to_field='email'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='CustomerUserApp.customeruser', to_field='email'),
        ),
    ]
