# Generated by Django 4.1.7 on 2023-03-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerUserApp', '0007_alter_customeruser_password'),
        ('transactionApp', '0004_rename_receiver_name_banktransaction_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='receiver',
            new_name='receiver_email',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='sender',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='sender_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='CustomerUserApp.customeruser'),
        ),
    ]
