# Generated by Django 4.1.7 on 2023-03-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerUserApp', '0008_alter_customeruser_password'),
        ('transactionApp', '0005_rename_receiver_banktransaction_receiver_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='sender_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='CustomerUserApp.customeruser'),
        ),
    ]
