# Generated by Django 4.1.7 on 2023-03-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerUserApp', '0002_customeruser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='user_permissions',
        ),
    ]
