# Generated by Django 4.1.7 on 2023-03-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerUserApp', '0003_remove_customeruser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='username',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterModelTable(
            name='customeruser',
            table='customer_user',
        ),
    ]
