# Generated by Django 4.1.7 on 2023-03-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerUserApp', '0005_customeruser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
